import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_node("bash_103_combining_commands", title="Bash: Combining Commands", author="Elizabeth Drellich and Nicole Feldman", estimated_time="30 minutes")
G.add_node("bash_command_line_101", title="Bash / Command Line 101", author="Nicole Feldman and Elizabeth Drellich", estimated_time="40 minutes")
G.add_node("bash_command_line_102", title="Bash: Searching and Organizing Files", author="Nicole Feldman and Elizabeth Drellich", estimated_time="30 minutes")
G.add_node("bash_conditionals_loops", title="Bash: Conditionals and Loops", author="Elizabeth Drellich", estimated_time="1 hour")
G.add_node("bash_scripts", title="Bash: Reusable Scripts", author="Elizabeth Drellich", estimated_time="1 hour")
G.add_node("citizen_science", title="Citizen Science", author="Rose Hartman", estimated_time="45 minutes")
G.add_node("data_management_basics", title="Research Data Management Basics", author="Ene Belleh", estimated_time="40 minutes")
G.add_node("data_storage_models", title="Types of Data Storage Solutions", author="Nicole Feldman", estimated_time="")
G.add_node("data_visualization_in_ggplot2", title="Data Visualization in ggplot2", author="Rose Hartman", estimated_time="60 min")
G.add_node("data_visualization_in_open_source_software", title="Data Visualization in Open Source Software", author="Rose Hartman", estimated_time="20 minutes")
G.add_node("data_visualization_in_seaborn", title="Data Visualization in seaborn", author="Rose Hartman", estimated_time="1 hour")
G.add_node("database_normalization", title="Database Normalization", author="Joy Payton", estimated_time="40 minutes")
G.add_node("demystifying_geospatial_data", title="Demystifying Geospatial Data", author="Elizabeth Drellich", estimated_time="15 minutes")
G.add_node("demystifying_python", title="Demystifying Python", author="Meredith Lee", estimated_time="20m")
G.add_node("demystifying_sql", title="Demystifying SQL", author="Peter Camacho", estimated_time="40 minutes")
G.add_node("directories_and_file_paths", title="Directories and File Paths", author="Meredith Lee", estimated_time="15m")
G.add_node("elements_of_maps", title="The Elements of Maps", author="Elizabeth Drellich", estimated_time="45 minutes")
G.add_node("geocode_lat_long", title="Encoding Geospatial Data: Latitude and Longitude", author="Elizabeth Drellich", estimated_time="15 minutes")
G.add_node("git_creation_and_tracking", title="Creating a Git Repository", author="Elizabeth Drellich", estimated_time="1 hour")
G.add_node("git_history_of_project", title="Exploring the History of your Git Repository", author="Elizabeth Drellich", estimated_time="30 minutes")
G.add_node("git_intro", title="Intro to Version Control", author="Rose Hartman", estimated_time="10 min")
G.add_node("git_setup_mac_and_linux", title="Setting Up Git on Mac and Linux", author="Rose Hartman", estimated_time="15 min")
G.add_node("git_setup_windows", title="Setting Up Git on Windows", author="Elizabeth Drellich", estimated_time="25 min")
G.add_node("how_to_troubleshoot", title="How to Troubleshoot", author="Joy Payton", estimated_time="30 minutes")
G.add_node("learning_to_learn", title="Learning to Learn Data Science", author="Rose Franzen", estimated_time="20 minutes")
G.add_node("omics_orientation", title="Omics Orientation", author="Meredith Lee", estimated_time="15m")
G.add_node("pandas_transform", title="Transform Data with pandas", author="Elizabeth Drellich", estimated_time="1 hour")
G.add_node("python_basics_writing_python_code", title="Python Basics: Writing Python Code", author="Meredith Lee", estimated_time="1 hour")
G.add_node("python_practice", title="Python Practice", author="Meredith Lee", estimated_time="1 hour")
G.add_node("r_basics_introduction", title="R Basics: Introduction", author="Joy Payton", estimated_time="1 hour")
G.add_node("r_basics_transform_data", title="R Basics: Transforming Data With dplyr", author="Joy Payton", estimated_time="1 hour")
G.add_node("r_basics_visualize_data", title="R Basics: Visualizing Data With ggplot2", author="Joy Payton", estimated_time="1 hour")
G.add_node("r_missing_values", title="Missing Values in R", author="Rose Hartman", estimated_time="45 min")
G.add_node("r_practice", title="R Practice", author="Meredith Lee", estimated_time="1 hour")
G.add_node("r_reshape_long_wide", title="Reshaping Data in R: Long and Wide Data", author="Joy Payton", estimated_time="1 hour")
G.add_node("reproducibility", title="Reproducibility, Generalizability, and Reuse", author="Joy Payton", estimated_time="1 hour")
G.add_node("sql_basics", title="SQL Basics", author="Peter Camacho", estimated_time="1 hour")
G.add_node("sql_intermediate", title="SQL, Intermediate Level", author="Peter Camacho", estimated_time="1 hour")
G.add_node("sql_joins", title="SQL Joins", author="Joy Payton", estimated_time="1 hour")
G.add_node("statistical_tests", title="Statistical Tests in Open Source Software", author="Rose Hartman", estimated_time="20 minutes (although reading through the linked tutorials may take much longer, depending on which tests you choose to read about)")
G.add_node("tidy_data", title="Tidy Data", author="Joy Payton", estimated_time="45 minutes")
G.add_node("using_redcap_api", title="Using the REDCap API", author="Joy Payton", estimated_time="1 hour")
G.add_edge("bash_103_combining_commands", "bash_command_line_101", link_type="internal_link")
G.add_edge("bash_103_combining_commands", "bash_command_line_102", link_type="internal_link")
G.add_edge("bash_103_combining_commands", "directories_and_file_paths", link_type="internal_link")
G.add_edge("bash_command_line_101", "directories_and_file_paths", link_type="internal_link")
G.add_edge("bash_command_line_101", "git_setup_windows", link_type="internal_link")
G.add_edge("bash_command_line_102", "bash_command_line_101", link_type="internal_link")
G.add_edge("bash_command_line_102", "directories_and_file_paths", link_type="internal_link")
G.add_edge("bash_conditionals_loops", "bash_command_line_101", link_type="internal_link")
G.add_edge("bash_conditionals_loops", "bash_command_line_102", link_type="internal_link")
G.add_edge("bash_conditionals_loops", "directories_and_file_paths", link_type="internal_link")
G.add_edge("bash_scripts", "bash_command_line_101", link_type="internal_link")
G.add_edge("bash_scripts", "reproducibility", link_type="internal_link")
G.add_edge("data_management_basics", "reproducibility", link_type="internal_link")
G.add_edge("data_visualization_in_ggplot2", "data_visualization_in_open_source_software", link_type="internal_link")
G.add_edge("data_visualization_in_ggplot2", "data_visualization_in_seaborn", link_type="internal_link")
G.add_edge("data_visualization_in_ggplot2", "r_basics_introduction", link_type="internal_link")
G.add_edge("data_visualization_in_ggplot2", "statistical_tests", link_type="internal_link")
G.add_edge("data_visualization_in_open_source_software", "data_visualization_in_ggplot2", link_type="internal_link")
G.add_edge("data_visualization_in_open_source_software", "data_visualization_in_seaborn", link_type="internal_link")
G.add_edge("data_visualization_in_open_source_software", "demystifying_python", link_type="internal_link")
G.add_edge("data_visualization_in_open_source_software", "r_basics_introduction", link_type="internal_link")
G.add_edge("data_visualization_in_seaborn", "data_visualization_in_ggplot2", link_type="internal_link")
G.add_edge("data_visualization_in_seaborn", "demystifying_python", link_type="internal_link")
G.add_edge("data_visualization_in_seaborn", "statistical_tests", link_type="internal_link")
G.add_edge("demystifying_python", "bash_command_line_101", link_type="internal_link")
G.add_edge("demystifying_python", "python_basics_writing_python_code", link_type="internal_link")
G.add_edge("demystifying_sql", "reproducibility", link_type="internal_link")
G.add_edge("git_creation_and_tracking", "git_setup_mac_and_linux", link_type="internal_link")
G.add_edge("git_creation_and_tracking", "git_setup_windows", link_type="internal_link")
G.add_edge("git_history_of_project", "git_creation_and_tracking", link_type="internal_link")
G.add_edge("git_setup_mac_and_linux", "git_setup_windows", link_type="internal_link")
G.add_edge("git_setup_windows", "git_setup_mac_and_linux", link_type="internal_link")
G.add_edge("learning_to_learn", "reproducibility", link_type="internal_link")
G.add_edge("pandas_transform", "python_basics_writing_python_code", link_type="internal_link")
G.add_edge("python_basics_writing_python_code", "demystifying_python", link_type="internal_link")
G.add_edge("python_practice", "data_visualization_in_seaborn", link_type="internal_link")
G.add_edge("python_practice", "demystifying_python", link_type="internal_link")
G.add_edge("python_practice", "pandas_transform", link_type="internal_link")
G.add_edge("python_practice", "python_basics_writing_python_code", link_type="internal_link")
G.add_edge("python_practice", "r_practice", link_type="internal_link")
G.add_edge("r_basics_introduction", "r_basics_transform_data", link_type="internal_link")
G.add_edge("r_basics_introduction", "r_basics_visualize_data", link_type="internal_link")
G.add_edge("r_basics_introduction", "reproducibility", link_type="internal_link")
G.add_edge("r_basics_transform_data", "r_basics_introduction", link_type="internal_link")
G.add_edge("r_basics_transform_data", "r_basics_visualize_data", link_type="internal_link")
G.add_edge("r_basics_visualize_data", "data_visualization_in_ggplot2", link_type="internal_link")
G.add_edge("r_basics_visualize_data", "r_basics_introduction", link_type="internal_link")
G.add_edge("r_basics_visualize_data", "r_basics_transform_data", link_type="internal_link")
G.add_edge("r_basics_visualize_data", "tidy_data", link_type="internal_link")
G.add_edge("r_missing_values", "r_basics_introduction", link_type="internal_link")
G.add_edge("r_missing_values", "r_basics_transform_data", link_type="internal_link")
G.add_edge("r_practice", "data_visualization_in_ggplot2", link_type="internal_link")
G.add_edge("r_practice", "python_practice", link_type="internal_link")
G.add_edge("r_practice", "r_basics_introduction", link_type="internal_link")
G.add_edge("r_practice", "r_basics_transform_data", link_type="internal_link")
G.add_edge("r_reshape_long_wide", "r_basics_introduction", link_type="internal_link")
G.add_edge("r_reshape_long_wide", "r_basics_transform_data", link_type="internal_link")
G.add_edge("r_reshape_long_wide", "tidy_data", link_type="internal_link")
G.add_edge("sql_basics", "demystifying_sql", link_type="internal_link")
G.add_edge("sql_intermediate", "demystifying_sql", link_type="internal_link")
G.add_edge("sql_intermediate", "sql_basics", link_type="internal_link")
G.add_edge("sql_joins", "database_normalization", link_type="internal_link")
G.add_edge("sql_joins", "sql_basics", link_type="internal_link")
G.add_edge("sql_joins", "sql_intermediate", link_type="internal_link")
G.add_edge("statistical_tests", "data_visualization_in_open_source_software", link_type="internal_link")
G.add_edge("statistical_tests", "python_basics_writing_python_code", link_type="internal_link")
G.add_edge("statistical_tests", "r_basics_introduction", link_type="internal_link")
G.add_edge("tidy_data", "reproducibility", link_type="internal_link")
G.add_edge("using_redcap_api", "reproducibility", link_type="internal_link")
