#theme: jekyll-theme-dinky
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: DART
description: Data and Analytics for Researchers Training Program
header_pages:
  - index.md
  - learners.md
  - educators.md
  - about.md
header_page_refs: ['Home','For Learners', 'For Educators', 'About']
