## What does "missing" look like in R?

## How to check for missing values

summary()

## Reading in data with missing values

read_csv(, na = c("", "NA")) # default
read_csv(, na = c("", "NA", "-999"))

## Assigning values to missing

As part of your data exploration, you may notice values for some variables that are impossible or extremely unlikely.

For example, take a look at the `y` variable in this data set.
It's on a scale from 1-5, so respondents weren't able to rate it as anything else.
And yet, there are a handful of -99 scores for this variable.
Depending on the data collection mechanism, these may be the result of typos during data entry or a systematic way of marking invalid or missing responses.
Either way, you don't want to treat those -99 scores as actual responses to the question (you can already see how they're distorting the estimate of the mean for that variable); instead, let's mark them missing so they'll be excluded from analysis.

mutate(df, y = ifelse(y == -99, NA, y))

Let's break that down.
We're using a `mutate` command to change the variable, and we're setting it to be conditional by using `ifelse`.
The `ifelse` command begins with a conditional test, in this case `ifelse(y == -99, NA, y)`, and for each value in `y`, it will run the test and return either `TRUE` or `FALSE`.
If it returns `TRUE`, then it assigns the next argument, in this case `NA`, which will mark that value missing.
If it returns `FALSE`, then it assigns the last argument, in this case `y`, which will leave the value untouched.
So for any `y` values that equal -99, we're asking it to replace them with `NA`, otherwise leave them as they were.

We could make this command more general by replacing all values that fall outside of the 1-5 scale with `NA`:

mutate(df, y = ifelse(y < 1 | y > 5, NA, y))

Here we're using the "or" operator `|` to combine two tests together.
So this checks whether each `y` value is less than 1 or greater than 5, and if so changes it to `NA`.
Otherwise it leaves it as it was.

As another example, consider the gestational age variable.
This variable records how many weeks the baby was in utero before birth.
Although there is some variability, full-term human pregnancies last about 40 weeks give or take two weeks.
Let's take a look at our data:

summary()
hist()

The overwhelming majority of the data fall within a reasonable range, but there are some outliers.
In particular, there is one baby listed with a gestational age of 405 weeks --- that is almost certainly a typo (perhaps it was meant to indicate 40 weeks and 5 days, but we can't know that for sure).
It is extremely unusual to deliver after 42 weeks because most doctors will induce labor at the end of 42 weeks if labor hasn't started naturally.
To provide a little cushion for the rare instances where birth does occur after 42 weeks, you might decide to use 45 weeks as a cutoff for what you will consider valid data:

mutate(df, y = ifelse(y > 45, NA, y))


## Working around missing values

## Filtering out missing values

prcomp()
