name: Link check

on:
  pull_request:
  workflow_dispatch:
    branches: [ "main" ]
    types: [opened, synchronize]
  schedule:
    - cron: "05 07 * * 1" #run at 7:05 am  every Mon

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.0

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue, bug